baseURL = 'http://localhost:1313/'
languageCode = 'zh-cn'
title = 'Trashwbin的个人空间'
theme = 'introduction'
DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true  # 为每种语言创建子目录

# 添加 Markdown 渲染配置
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许 HTML
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    style = "monokai"

[params]
    themeStyle = "light"
    favicon = "favicon.ico"
    showRSSButton = false
    fadeIn = true
    fadeInIndex = false
    
    # 添加导航设置
    showMenu = true
    showServices = true
    showProjects = true
    showBlog = true
    showContact = true
    showAbout = true
    
    # 个人信息
    firstName = "Abin"
    lastName = ""
    
    # 社交媒体链接
    [[params.social]]
        url = "https://gitee.com/trashwbin"
        icon = "fab fa-git-alt"
        
    [[params.social]]
        url = "mailto:Trashwbin@gmail.com"
        icon = "fas fa-envelope"

[languages]
    [languages.zh]
        languageName = "中文"
        contentDir = "content/zh"
        weight = 1
        title = "Trashwbin的个人空间"
        
        [languages.zh.params]
            description = "一名热爱技术的开发者"
            tagLine = "一名热爱技术的开发者"
            footerText = "用 ❤️ 制作"

    [languages.en]
        languageName = "English"
        contentDir = "content/en"
        weight = 2
        title = "Trashwbin's Personal Space"
        
        [languages.en.params]
            description = "A passionate developer"
            tagLine = "A passionate developer"
            footerText = "Made with ❤️"
